spring:
  application:
    name: accounts-service
  freemarker:
    enabled: false

server:
  port: 2222

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
    instance:
      leaseRenewalIntervalInSeconds: 5  # DON NOT DO THIS IN PRODUCTION
